# Generated by Django 5.0.4 on 2024-04-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='', max_length=5, unique=True)),
                ('category', models.CharField(default='', max_length=15)),
                ('description', models.CharField(default='', max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
    ]
