# Generated by Django 5.0.4 on 2024-04-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0002_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
