# Generated by Django 5.0.4 on 2024-05-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0005_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='description',
            field=models.TextField(),
        ),
    ]
