# Generated by Django 5.0.4 on 2024-05-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0006_alter_cotizacion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='ReceiverAddress',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
